defaults:
    - config
    - _self_

lattice:
    path: ./lattice/sns_ring_nux6.175_nuy6.175_sol.lattice
    seq: rnginjsol
    apertures: false
    foil: false
    impedance:
        xy: false
        z: false
    spacecharge:
        xy: false
        z: false
    rf: false
    solenoid: true

bunch:
    mass: 0.93827231
    energy: 0.800

paint:
    amp1: 10.0
    amp2: 0.0
    phase1: 0.0
    phase2: 0.0
    include_spacecharge: false

turns_inj: 300
turns_store: 0
macros_per_turn: 100
write_bunch_freq: 100
